M48
; DRILL file {KiCad 8.0.5} date 2024-10-09T23:57:25+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-09T23:57:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.178Y-2.405
X5.178Y-2.485
X5.378Y-2.445
T2
X4.9063Y-3.7
X5.6937Y-3.7
M30
